#!/usr/bin/env node

var http = require('http')

const port = process.env.PORT || 80

const server = http.createServer((req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain')
  res.end('666\n')
})

server.listen(port, () => {
  console.log(`服务器运行在 http://0.0.0.0:${port}/`)
})